### ISSUE TITLE
Update to new version

### ISSUE THREAD

**Issue by q-wertz** [popey/spot-snap#4]
[Version 0.3.0](https://github.com/xou816/spot/releases/tag/0.3.0) is released.

Could you update the snap to the newest version? The snap still seems to be on 0.1.15.

**Comment by popey** [comment]
Sorry, I can't. I no longer use the snap. But more importantly, the newer versions rely on packages which aren't in the Ubuntu archive, and are somewhat painful to build, and I don't have the time.

**Comment by q-wertz** [comment]
Thanks for the information :+1: :)

**Comment by popey** [comment]
This is now fixed.
