### ISSUE TITLE
Update to 0.4.1

### ISSUE THREAD

**Issue by Recydywa** [popey/spot-snap#6]
There was a new release of Spot on 10th April 2024. It is titled as maintenance release, but it's always nice to have those fixes.

Especially the that there is also this in the description of 0.4.1 release: This release includes a major fix for Spotify's API. 

https://github.com/xou816/spot/releases/tag/0.4.1

**Comment by popey** [comment]
Thanks for the issue. I am aware, and have tried to update the snap, but it's failing to build here.

**Comment by Recydywa** [comment]
Yes I saw that there were changes made 3 days ago, so I thought you must have done something about that new version.

Thank you. You do a very good job maintaining all those snaps.
